### ISSUE TITLE
varsel() does not work with negative binomial model

### ISSUE THREAD

**Issue by yongparkpitt** [stan-dev/projpred#101]
I fitted a negative binomial model like this:

fit <- stan_glm(family=neg_binomial_2(), diabetes ~  gender + anxietyRate_s + smokingRate_s  + obesityRate_s, offset = log(diabetesAtRisk), data=data2015)

cvs <- cv_varsel(fit, cv_method='LOO')
Error in get(extend_family_specific, mode = "function") : 
  object 'extend_family_neg_binomial_2' of mode 'function' was not found

Any suggestion how I can solve the problem?

Yongseok

**Comment by AlejandroCatalina** [comment]
Hi!

First of all, thanks for your interest in using projpred. 

Unfortunately, models outside of the exponential family are not implemented for now, and that applies to negative binomial models. We are working on making projpred available for a wide class of models outside of the exponential family and hopefully we'll bring support for negative binomial models soon.

**Comment by AlejandroCatalina** [comment]
This is already mentioned in #67, so I'm closing this one.
