### ISSUE TITLE
Transformation bug in `compute_lpd()`?

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#104]
In `compute_lpd()`, I think line https://github.com/stan-dev/projpred/blob/f3962c0672d3ddbe6e184625c0e549a0392ba7c9/R/methods.R#L224 needs to be replaced by
```r
if (transform) pred <- proj$family$linkfun(pred)
```
since in case of `transform = TRUE`, `pred` is on response scale and so needs to be transformed to the linear predictor scale in order to be passed to `proj$family$ll_fun()`. In case of `transform = FALSE`, `pred` is already on the linear predictor scale, so it doesn't need to be modified. But I'm not 100% sure, so I'm posting it here on the issue tracker instead of directly creating a PR.

**Comment by AlejandroCatalina** [comment]
I believe the predictions are by default on the response scale. Therefore we only need to revert the link function if the user wants the linear prediction. This should be addressed by the tests, let me check.

**Comment by AlejandroCatalina** [comment]
Exactly, you can check that the `lpd` slot of the predictions is identical regardless of `transform`.

**Comment by fweber144** [comment]
Sorry, my bad---I thought that `pred` had to be on the linear predictor scale in order to be passed to `proj$family$ll_fun()` but that's not the case. I was also confused by the comment https://github.com/stan-dev/projpred/blob/f3962c0672d3ddbe6e184625c0e549a0392ba7c9/R/methods.R#L223 which probably needs to be adopted (or removed). I can handle that in PR #92.

**Comment by fweber144** [comment]
I removed that comment in PR #92 (commit 298bc3e8a27cebef572692a892ddf7f90bf3f49e).
