### ISSUE TITLE
Output `lpd` of `proj_linpred()` not averaged in case of `integrated = TRUE`

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#106]
At least for the `gaussian()` family, specifying `integrated = TRUE` in `proj_linpred()` leads to an output element `lpd` which is probably incorrect. Consider the following reprex:
```r
library(projpred)
library(rstanarm)
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
myfit <- stan_glm(y ~ V1 + V2 + V3 + V4 + V5,
                  family = gaussian(),
                  data = mydat,
                  prior = hs(df = 1, global_scale = 0.01),
                  seed = 1140350788)

mylinpred <- proj_linpred(myfit,
                          solution_terms = c("V3", "V2"),
                          newdata = mydat[1:3, , drop = FALSE],
                          integrated = TRUE,
                          ndraws = 20)
```
Then element `mylinpred$lpd` seems to be incorrect as it is of length 60 (= 3 * 20) here, but is supposed to be of length 3 (just like element `mylinpred$pred`). I guess the problem is related to the lines https://github.com/stan-dev/projpred/blob/f3962c0672d3ddbe6e184625c0e549a0392ba7c9/R/methods.R#L226-L230 which should perhaps be preceded by something like
```r
if (is.matrix(lpd) && ncol(lpd) == 1) {
  lpd <- as.vector(lpd)
}
```
since in this reprex, the `proj$family$ll_fun()` call by `compute_lpd()` returns a matrix with 1 column and so `!is.null(dim(lpd))` evaluates to `TRUE`.

**Comment by fweber144** [comment]
Furthermore, I wonder whether in the `apply()` call in line https://github.com/stan-dev/projpred/blob/f3962c0672d3ddbe6e184625c0e549a0392ba7c9/R/methods.R#L227 should really be using `MARGIN = 1` and not `MARGIN = 2`. But I haven't had the case `is.matrix(lpd) && ncol(lpd) > 1` yet, so I can't tell. (Note that with my suggested introduction of
```r
if (is.matrix(lpd) && ncol(lpd) == 1) {
  lpd <- as.vector(lpd)
}
```
that `apply()` call wouldn't be used in this reprex anyway.)

**Comment by AlejandroCatalina** [comment]
Fixed in https://github.com/stan-dev/projpred/commit/26d83e63c8a7f28bff44a9be002ed72c65ed273f.

**Comment by fweber144** [comment]
Thanks for addressing this in commit 26d83e63c8a7f28bff44a9be002ed72c65ed273f. However, now specifying `integrated = TRUE` causes the LPD to be averaged over the posterior draws, which I think is a different approach than taking the LPD at the averaged posterior draws (or the averaged linear predictors, but that would require `!transform` in the current implementation), at least in general. Correct me if I am wrong. Personally, I would think that taking the LPD at the averaged posterior draws (or the averaged linear predictors) would be more appropriate here. Do you want me to create a PR for that so you can see what I mean?

**Comment by AlejandroCatalina** [comment]
Yeah I know what you mean, I was a bit quick at addressing this one, I’ll reformulate it.

Best,
Alejandro

**Comment by AlejandroCatalina** [comment]
Fixed here 33984b0c0f98c8369dc70d9828ffe6d9eb897722

**Comment by fweber144** [comment]
Thanks. Now there's only a minor inconsistency: The reprex above gives
```r
str(mylinpred)
# List of 2
# $ pred: num [1:3] 1.17071 0.72188 0.00114
# $ lpd : num [1, 1:3] -2.33 -2.04 -1.98
```
so I guess `mylinpred$lpd` should be coerced to a vector, too. I think you can achieve this be replacing https://github.com/stan-dev/projpred/blob/33984b0c0f98c8369dc70d9828ffe6d9eb897722/R/methods.R#L205-L208 with
```r
return(nlist(pred, lpd = drop(t(compute_lpd( 
  ynew = ynew, pred = pred, proj = proj, weights = weights, 
  integrated = integrated, transform = transform 
)))))
```
so just introducing a `drop()` call around the `t(compute_lpd([...]))` call.

**Comment by AlejandroCatalina** [comment]
Yeah I thought about this. I think it makes sense to drop the first dimension if it’s only a vector.

Best,
Alejandro

**Comment by fweber144** [comment]
Argh, now there is an inconsistency in case of N = 1 (and `integrated = FALSE`):
```r
# devtools::load_all(".")
library(projpred)
library(rstanarm)
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
myfit <- stan_glm(y ~ V1 + V2 + V3 + V4 + V5,
                  family = gaussian(),
                  data = mydat,
                  prior = hs(df = 1, global_scale = 0.01),
                  seed = 1140350788)

mylinpred1 <- proj_linpred(myfit,
                           solution_terms = c("V3", "V2"),
                           newdata = mydat[1, , drop = FALSE],
                           ndraws = 20)
str(mylinpred1)
# List of 2
#  $ pred: num [1:20, 1] 0.806 1.315 1.011 1.095 1.154 ...
#   ..- attr(*, "dimnames")=List of 2
#   .. ..$ : NULL
#   .. ..$ : chr "1"
#  $ lpd : num [1:20] -2.22 -2.39 -2.27 -2.31 -2.32 ...
mylinpred2 <- proj_linpred(myfit,
                           solution_terms = c("V3", "V2"),
                           newdata = mydat[1:2, , drop = FALSE],
                           ndraws = 20)
str(mylinpred2)
# List of 2
#  $ pred: num [1:20, 1:2] 1.173 1.645 0.911 1.397 0.744 ...
#   ..- attr(*, "dimnames")=List of 2
#   .. ..$ : NULL
#   .. ..$ : chr [1:2] "1" "2"
#  $ lpd : num [1:20, 1:2] -2.34 -2.49 -2.25 -2.41 -2.23 ...
#   ..- attr(*, "dimnames")=List of 2
#   .. ..$ : NULL
#   .. ..$ : chr [1:2] "1" "2"

myprojpred1 <- proj_predict(myfit,
                            solution_terms = c("V3", "V2"),
                            newdata = mydat[1, , drop = FALSE],
                            ndraws = 20)
str(myprojpred1)
# num [1, 1:20] 2.499 2.349 7.454 1.905 0.392 ...
myprojpred2 <- proj_predict(myfit,
                            solution_terms = c("V3", "V2"),
                            newdata = mydat[1:2, , drop = FALSE],
                            ndraws = 20)
str(myprojpred2)
# num [1:20, 1:2] -0.21 -2.744 1.281 4.734 0.163 ...
```
I'll have a look at how this could be solved.

**Comment by fweber144** [comment]
Probably the simplest solution would be to replace https://github.com/stan-dev/projpred/blob/dc99186b1065c9984e279d44c5d4868bc38805d4/R/methods.R#L232 by
```r
lpd <- t(lpd)
if (nrow(lpd) == 1) {
  lpd <- drop(lpd)
}
```

**Comment by AlejandroCatalina** [comment]
Right I see! I’ll take a look as well. Thanks for noticing.

Best,
Alejandro

**Comment by fweber144** [comment]
The problem with `proj_predict()` should have existed long before. I think replacing https://github.com/stan-dev/projpred/blob/dc99186b1065c9984e279d44c5d4868bc38805d4/R/methods.R#L253-L255 by
```r
do.call(rbind, lapply(draw_inds, function(i) {
  proj$family$ppd(mu[, i], proj$dis[i], weights)
}))
```
should fix it.

**Comment by fweber144** [comment]
Combined in PR #112.
