### ISSUE TITLE
Transpose output `lpd` of `proj_linpred()`?

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#107]
This reprex:
```r
library(projpred)
library(rstanarm)
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
myfit <- stan_glm(y ~ V1 + V2 + V3 + V4 + V5,
                  family = gaussian(),
                  data = mydat,
                  prior = hs(df = 1, global_scale = 0.01),
                  seed = 1140350788)

mylinpred <- proj_linpred(myfit,
                          solution_terms = c("V3", "V2"),
                          newdata = mydat[1:3, , drop = FALSE],
                          ndraws = 20)
str(mylinpred)
```
shows that (in the default case of `integrated = FALSE`) either output element `mylinpred$pred` or output element `mylinpred$lpd` should probably be transposed (I guess it should be element `mylinpred$lpd` to match the behavior of `proj_predict()` and also to match rstan's convention of having as many rows as posterior draws).

**Comment by AlejandroCatalina** [comment]
I have transposed both `pred` and `lpd` in `proj_linpred`.

**Comment by fweber144** [comment]
Only one of them needed to be transposed; as mentioned above:

> either output element `mylinpred$pred` or output element `mylinpred$lpd` should probably be transposed (I guess it should be element `mylinpred$lpd` to match the behavior of `proj_predict()` and also to match rstan's convention of having as many rows as posterior draws).

**Comment by AlejandroCatalina** [comment]
Right, I addressed this on latest develop (still to be uploaded).

Best,
Alejandro
