### ISSUE TITLE
Typo (`seq_long`) in `.get_kfold()`?

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#108]
In `.get_kfold()` (line https://github.com/stan-dev/projpred/blob/f3962c0672d3ddbe6e184625c0e549a0392ba7c9/R/cv_varsel.R#L761), there is a `seq_long()` call but that function doesn't seem to be defined. Is this a typo? `seq_along()` would be the nearest match, but I guess it should be `seq_len()`, right?

**Comment by AlejandroCatalina** [comment]
Exactly, it’s a typo.

Best,
Alejandro
