### ISSUE TITLE
Undefined function `where`

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#109]
In `print.vselsummary()` (line https://github.com/stan-dev/projpred/blob/f3962c0672d3ddbe6e184625c0e549a0392ba7c9/R/methods.R#L578), there is a `where()` call but that function doesn't seem to be defined. Is this supposed to be `tidyselect::where()`? If yes, then `tidyselect` also needs to be added to the `Imports` field in file `DESCRIPTION`, I guess.

**Comment by AlejandroCatalina** [comment]
I’ll fix this. Thanks!

Best,
Alejandro

**Comment by AlejandroCatalina** [comment]
Fixed in develop.

**Comment by fweber144** [comment]
Thanks for addressing this in commits 62e5ba955b6dddb15ba777e0d9df6fa81a9a84af and daeb377b85dd50edf3c81158807aa620c4ce975b which removes R CMD check's `no visible binding for global variable` note. However, I hadn't checked whether `where()` was exported or not from tidyselect. Sorry for that. As you found out, it is not exported (so `:::` is required). Unfortunately, this causes a new note in R CMD check (`Unexported object imported by a ':::' call`). A possible remedy is to define
```r
where <- utils::getFromNamespace("where", "tidyselect")
```
somewhere. I'll include this in my PR #92.

**Comment by AlejandroCatalina** [comment]
That’s fine if you can include it, thanks!

Best,
Alejandro

**Comment by fweber144** [comment]
Included in PR #92 (commit 826c2675cc6b62e2fd28f221ca37deaf1a875039).
