### ISSUE TITLE
cv_varsel error since updated R and all packages

### ISSUE THREAD

**Issue by lkschwarz** [stan-dev/projpred#126]
I was following the steps from a post by Aki Vehtari to perform projection predictive variable selection:
https://avehtari.github.io/modelselection/bodyfat.html

With my data and with the data provided in the post, I am getting an error message when I use cv_varsel:
"Error: $ operator is invalid for atomic vectors"

System (I recently updated R and all packages):
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
attached base packages:
stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
corrplot_0.84   bayesplot_1.8.0   ggplot2_3.3.3   projpred_2.0.2  loo_2.4.1  rstanarm_2.21.1  Rcpp_1.0.6     

Here is the code (basically copied from the post). I have attached the data from the post:
library(rstanarm)
options(mc.cores = parallel::detectCores())
library(loo)
library(projpred)
library(ggplot2)
library(bayesplot)
theme_set(bayesplot::theme_default(base_family = "sans"))
library(corrplot)
SEED=1513306866

setwd("C:/....")

df <- read.table("bodyfat.csv", header = T, sep = ",")
df[,4:19] <- scale(df[,4:19])

df <- df[df$siri>0,] # no-one can have 0% body fat
y <- df[,"siri"]
df <- as.data.frame(df)
n <- nrow(df)

pred <- c("age", "weight", "height", "neck", "chest", "abdomen", "hip", 
          "thigh", "knee", "ankle", "biceps", "forearm", "wrist")
target <- "siri"
formula <- paste("siri~", paste(pred, collapse = "+"))
p <- length(pred)

corrplot(cor(df[, c(target,pred)]))

p0 <- 5 # prior guess for the number of relevant variables
tau0 <- p0/(p-p0) * 1/sqrt(n)
rhs_prior <- hs(global_scale=tau0)
fitrhs <- stan_glm(formula, data = df, prior=rhs_prior, QR=TRUE, 
                   seed=SEED, refresh=0)
summary(fitrhs)

yrep <- posterior_predict(fitrhs, draws = 50)
ppc_dens_overlay(y, yrep)

mcmc_areas(as.matrix(fitrhs)[,2:14])

fitrhs_cvvs <- cv_varsel(fitrhs, method = 'forward', cv_method = 'LOO',
                         nloo = n, verbose = FALSE)
[bodyfat.txt](https://github.com/stan-dev/projpred/files/6429733/bodyfat.txt)

**Comment by AlejandroCatalina** [comment]
The issue comes from the `formula` object, as it's a string whereas `projpred` expects a `formula`. Simply doing `formula <- as.formula(paste("siri~", paste(pred, collapse = "+")))` makes the code run alright. I'll add a line to explicitly verify that the formula object is as expected. This is fixed in `develop` branch in commit c51700d.

Thanks for reporting!
