### ISSUE TITLE
Poisson example in GLMM vignette

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#137]
Even after #133, the Poisson example in the GLMM vignette stays strange: For the hierarchical SD of `(1 | obs)`, the projection gives exactly 1 across all projected draws. When looking closer at the submodel from the first projected draw, I got this output:
```
Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
 Family: poisson  ( log )
Formula: .phen_pois.1 ~ cofactor + (1 | obs)
   Data: data
Weights: weights
     AIC      BIC   logLik deviance df.resid 
     Inf      Inf     -Inf      Inf      197 
Random effects:
 Groups Name        Std.Dev.
 obs    (Intercept) 1       
Number of obs: 200, groups:  obs, 200
Fixed Effects:
(Intercept)     cofactor  
    -1.9833       0.2467  
optimizer (Nelder_Mead) convergence code: 0 (OK) ; 14000 optimizer warnings; 1 lme4 warnings
```
The optimizer and lme4 warnings there at the end might already indicate an issue. Perhaps it's the try to model overdispersion by including `(1 | obs)` (where `obs` has a one level per observation) which causes problems here. (Note that in the [currently published vignette](https://mc-stan.org/projpred/articles/quickstart_glmm.html#poisson-example-1), it *seems* like the hierarchical SD is not exactly 1, but that's only due to the former use of the empirical SD of the random effects instead of their hierarchical SD, see #74.)

Anyway, since the vignette already takes very long to run through, perhaps simply omit this Poisson example? Or completely re-organize the whole GLMM vignette? In my opinion, a single example would be enough. And since the Bernoulli family is probably the most common one for *generalized* linear (mixed) models, I would choose a Bernoulli example. The `VerbAgg` example from the current vignette is nice, but it has a lot of observations (even when restricting it to 50 individuals) and the varsel (as well as the CV varsel) plot looks strange. Perhaps consider the `MASS::bacteria` dataset instead, e.g. with the formula `y ~ week * trt + (1 | ID)`?

**Comment by AlejandroCatalina** [comment]
That’s reasonable. We just wanted to include enough variation but I agree one example would be enough. I don’t have time right now to remake the vignette so it’ll have to stay for a while at least. If you want to give it a shot I can help with anything.

Best,
Alejandro

**Comment by fweber144** [comment]
Of course, I understand that. If I get the time, I can create or at least draft a PR for this. But as you said, it's not too important.

**Comment by fweber144** [comment]
Fixed in `develop`, so a corresponding label may be added here.
