### ISSUE TITLE
GLMs: Coefficient for reference level of categorical predictors

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#149]
On branch `develop` (commit 96d8e11d6f0ad0a1f7836c51700cb676b364bee5), this reprex:
```r
options(mc.cores = parallel::detectCores(logical = FALSE))
data("kidiq", package = "rstanarm")
kidiq_gr <- within(kidiq, {
  agegr <- cut(mom_age,
               breaks = unique(quantile(mom_age)),
               include.lowest = TRUE)
  levels(agegr) <- paste0("lvl", seq_len(nlevels(agegr)))
})
kidiq_gr <- head(kidiq_gr, 45)
fit_gauss <- rstanarm::stan_glm(
  kid_score ~ mom_iq + agegr,
  data = kidiq_gr,
  iter = 500,
  seed = 734572
)

library(projpred)
prj <- project(fit_gauss, solution_terms = c("agegr"), ndraws = 25)
colnames(as.matrix(prj))
```
gives
```
[1] "b_Intercept" "b_agegrlvl1" "b_agegrlvl2" "b_agegrlvl3" "b_agegrlvl4" "sigma"
```
(so the output matrix includes a coefficient for the reference level) whereas
```
colnames(as.matrix(fit_gauss))
```
(correctly) gives
```
[1] "(Intercept)" "mom_iq"      "agegrlvl2"   "agegrlvl3"   "agegrlvl4"   "sigma"
```

**Comment by AlejandroCatalina** [comment]
I'm actually not sure how to label this because this is something we did on purpose and should be equivalent to having C-1 terms. I can see that maybe the issue is that we are breaking a bit from the reference model, so it's good to think about it. I remember something broke somewhere if we did not include the reference categorical level, though.

**Comment by fweber144** [comment]
To be honest, I've never seen a regression model where the reference level of a categorical predictor gets its own coefficient. Perhaps it works here due to the regularization (argument `regul` has a default of  `1e-4`). But usually, such a coefficient should be unidentifiable.

**Comment by fweber144** [comment]
Btw, it's already within the fitted submodel (of class `subfit`) that the reference level gets its own coefficient. Since class `subfit` is related to GLMs, only GLMs should be concerned by this issue. To see that for non-GLMs, the reference level does not get a coefficient, see the following modified reprex from above:
```r
library(rstanarm)
options(mc.cores = parallel::detectCores(logical = FALSE))
dat <- mgcv::gamSim(1, n = 400, scale = 2) ## simulate 4 term additive truth
## Now add 20 level random effect`fac'...
dat$fac <- fac <- as.factor(sample(1:20, 400, replace = TRUE))
dat$y <- dat$y + model.matrix(~ fac - 1) %*% rnorm(20) * .5
dat$facfix <- facfix <- as.factor(sample(1:3, 400, replace = TRUE))
dat$y <- dat$y + model.matrix(~ facfix - 1) %*% rnorm(3) * .5
br <- stan_glmer(y ~ x1 + facfix + (1 | fac), data = dat,
                 iter = 500, # for example speed
                 seed = 1140350788)
myproj <- project(br,
                  solution_terms = c("x1", "facfix", "(1 | fac)"),
                  nclusters = 2)
myprjmat <- as.matrix(myproj)
colnames(myprjmat)

```
which gives:
```
 [1] "b_Intercept"         "b_x1"                "b_facfix2"          
 [4] "b_facfix3"           "sd_fac__Intercept"   "r_fac[1,Intercept]" 
 [7] "r_fac[2,Intercept]"  "r_fac[3,Intercept]"  "r_fac[4,Intercept]" 
[10] "r_fac[5,Intercept]"  "r_fac[6,Intercept]"  "r_fac[7,Intercept]" 
[13] "r_fac[8,Intercept]"  "r_fac[9,Intercept]"  "r_fac[10,Intercept]"
[16] "r_fac[11,Intercept]" "r_fac[12,Intercept]" "r_fac[13,Intercept]"
[19] "r_fac[14,Intercept]" "r_fac[15,Intercept]" "r_fac[16,Intercept]"
[22] "r_fac[17,Intercept]" "r_fac[18,Intercept]" "r_fac[19,Intercept]"
[25] "r_fac[20,Intercept]" "sigma"
```
i.e. lacking `"b_facfix1"`.

**Comment by fweber144** [comment]
To avoid any misunderstandings: I'm assuming that projpred uses dummy coding for categorical predictors and not a different parameterization which omits the intercept.

**Comment by fweber144** [comment]
Minor update: In the very first projpred version (0.7.0), the documentation for argument `regul` of `project()` said:

> Amount of regularization in the projection. Usually there is no need for regularization, but sometimes for some models the projection can be ill-behaved and we need to add some regularization to avoid numerical problems. Default is 1e-9.

So my comment [above](https://github.com/stan-dev/projpred/issues/149#issuecomment-1833426661) might have been wrong and some regularization should perhaps indeed be the default. However, for GLMMs, GAMs, and GAMMs as well as for the augmented-data projection, no regularization takes place. So having a default of no regularization for GLMs would be more consistent.
