### ISSUE TITLE
`search_terms` for ordering of terms

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#155]
[This answer in the Stan Forums](https://discourse.mc-stan.org/t/projection-predictive-feature-selection-for-multilevel-phylogenetic-models/21402/4) suggests that `search_terms` may be used to define the order of the terms as they enter the search. If this is correct, I think it should be documented (I couldn't find it in the documentation).

**Comment by AlejandroCatalina** [comment]
In a way yes. This argument allows for a lot of flexibility and all use cases might be difficult to document. However, we have already a draft for couple use cases under the develop branch I believe.

On another note, it probably does not make sense to define the whole ordering of the solution but it can indeed be used to define some terms that have to be introduced in the projection before some others, but that’s not exactly the exploration order but rather the order in the solution.

Un saludo,
Alejandro Catalina Feliú

**Comment by fweber144** [comment]
Yeah, I see. It's not an urgent issue; I just wanted to point this out so it doesn't get forgotten.

**Comment by fweber144** [comment]
Just to have this in one place: [This thread](https://discourse.mc-stan.org/t/advice-on-using-search-terms-in-projpred/22846) might provide another starting point for explaining `search_terms` in the docs.

**Comment by jfiksel** [comment]
Following up on this, as the use of search_terms is very confusing to me. I would like to use search_terms to force a subset of variables into the model--i.e. if I have variables x1, x2, ..., x10, I would like the "base model" to be 1 + x1 + x2 and then to use projection to select one or more of variables x3, x4, ..., x10 to add to this model. Is this possible?

**Comment by AlejandroCatalina** [comment]
It is, you just need to make sure all elements of search terms contain “x1 + x2” except for three elements that are ”1”,  “x1” and “x2” respectively.

Best,
Alex
________________________________

**Comment by jfiksel** [comment]
Hi @AlejandroCatalina thanks for the response. I'm still not sure I understand how this is supposed to function. Here is a small example using mtcars, where I attempt to force the variables vs and qsec into the model using search_terms. When using search_terms, the results seem to be exactly the same as when not using search_terms. I'm not sure if this is a bug or if I'm using search_terms incorrectly.

```
library(rstanarm)
library(projpred)
data("mtcars")
modbrms <- stan_glm(mpg ~ vs + wt + qsec + am + cyl, 
                    family=gaussian(),
                    data = mtcars)
refmodel <- get_refmodel(modbrms)
### First without search_terms
modvarsel <- varsel(refmodel)
# Below gives "wt"   "cyl"  "qsec" "am"   "vs" as order
modvarsel$solution_terms
### Now using search_terms to force vs and qsec in model
st <- c("1", "vs", "qsec", "vs+qsec+am", "vs + qsec +wt", "vs+qsec+cyl")
modvarsel2 <- varsel(refmodel, search_terms = st)
### Still same order of  "wt"   "cyl"  "qsec" "am"   "vs" 
modvarsel2$solution_terms
``` 

Session Info:

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rejection 
 
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] projpred_2.0.5.9000 rstanarm_2.21.1     Rcpp_1.0.7    
```

**Comment by fweber144** [comment]
> Hi @AlejandroCatalina thanks for the response. I'm still not sure I understand how this is supposed to function. Here is a small example using mtcars, where I attempt to force the variables vs and qsec into the model using search_terms. When using search_terms, the results seem to be exactly the same as when not using search_terms. I'm not sure if this is a bug or if I'm using search_terms incorrectly.
> 
> ```
> library(rstanarm)
> library(projpred)
> data("mtcars")
> modbrms <- stan_glm(mpg ~ vs + wt + qsec + am + cyl, 
>                     family=gaussian(),
>                     data = mtcars)
> refmodel <- get_refmodel(modbrms)
> ### First without search_terms
> modvarsel <- varsel(refmodel)
> # Below gives "wt"   "cyl"  "qsec" "am"   "vs" as order
> modvarsel$solution_terms
> ### Now using search_terms to force vs and qsec in model
> st <- c("1", "vs", "qsec", "vs+qsec+am", "vs + qsec +wt", "vs+qsec+cyl")
> modvarsel2 <- varsel(refmodel, search_terms = st)
> ### Still same order of  "wt"   "cyl"  "qsec" "am"   "vs" 
> modvarsel2$solution_terms
> ```
> 
> Session Info:
> 
> ```
> R version 4.1.0 (2021-05-18)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Catalina 10.15.7
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
> 
> Random number generation:
>  RNG:     Mersenne-Twister 
>  Normal:  Inversion 
>  Sample:  Rejection 
>  
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] projpred_2.0.5.9000 rstanarm_2.21.1     Rcpp_1.0.7    
> ```

I think I found the reason why you didn't see any impact of argument `search_terms`: This argument only takes effect in case of a forward search and in your case, the `method = NULL` default means that L1 search is used (see `?varsel`). If you specify `method = "forward"`, it seems to work:
```r
modvarsel2 <- varsel(refmodel, method = "forward", search_terms = st)
```
I'll document that `search_terms` only takes effect in case of a forward search and I'll think about setting `method` to `"forward"` internally if its input is `NULL`. I'll also try to improve the documentation with respect to how `search_terms` needs to be specified (this is a question which came up frequently in the links above).
