### ISSUE TITLE
Documentation of `formula` for additive models

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#156]
In the documentation for argument `formula` of `get_refmodel.default()` and `init_refmodel()`, I think some additional information about additive models would be helpful (or at least where to find it). I'm not too familiar with the projpred implementation for additive models, so I guess you (the projpred authors) can add that information more easily.

**Comment by fweber144** [comment]
Might be fixed in `develop` now (I'm not sure if my added documentation is sufficient).

**Comment by fweber144** [comment]
Just stumbled across your comment

> This happens because we have not implemented parsing support for by syntax in smooth terms. It is desirable to have but we haven’t had the time yet.

from #145. Are you sure the group-level independent smoothers (`s(x, by = g)`) are supported?

**Comment by AlejandroCatalina** [comment]
No, that’s what I said, it is not implemented, or at least not properly .

Best,
Alex
________________________________

**Comment by fweber144** [comment]
Ok, then I probably got you wrong in this thread here.

**Comment by fweber144** [comment]
There are several things I'd like to point out here:

First of all, to see why the `split_formula()` thing is problematic, use `varsel()` instead of `project()`:
```r
data("lasrosas.corn", package = "agridat")
lasrosas.corn$year <- as.factor(lasrosas.corn$year)
library(rstanarm)
options(mc.cores = parallel::detectCores(logical = FALSE))
refm_fit <- stan_gamm4(
  yield ~ year + topo + s(bv, by = topo),
  family = gaussian(),
  data = lasrosas.corn,
  seed = 4919670
)
library(projpred)
vs <- varsel(refm_fit, ndraws_pred = 20, seed = 15705533)
```
which gives
```
Error in class(ff) <- "formula" : cannot set attribute on a symbol
In addition: Warning messages:
1: In init_refmodel(object = object, data = data, formula = formula,  :
  Support for additive models is still experimental.
```

Secondly, the same thing happens with `t2()` instead of `s()` (here demonstrated with two predictors in the `t2()` call):
```r
refm_fit <- stan_gamm4(
  yield ~ year + topo + t2(bv, nitro, by = topo),
  family = gaussian(),
  data = lasrosas.corn,
  seed = 4919670
)
prj <- project(
  refm_fit,
  solution_terms = c("topo + t2(bv, nitro, by = topo)", "year"),
  ndraws = 25,
  seed = 15705533
)
vs <- varsel(refm_fit, ndraws_pred = 20, seed = 15705533)
```

Thirdly, the same thing happens with argument `bs` (here shown with `bs = "re"`):
```r
refm_fit <- stan_gamm4(
  yield ~ year + s(topo, bs = "re"),
  family = gaussian(),
  data = lasrosas.corn,
  seed = 4919670
)
prj <- project(
  refm_fit,
  solution_terms = c("s(topo, bs = \"re\")", "year"),
  ndraws = 25,
  seed = 15705533
)
vs <- varsel(refm_fit, ndraws_pred = 20, seed = 15705533)
```
(this time giving
```
Error in terms.formula(formula) : argument is not a valid model
In addition: Warning messages:
1: In init_refmodel(object = object, data = data, formula = formula,  :
  Support for additive models is still experimental.
2: invalid formula ". ~ 1 + s(topo, bs = \"re\") + year + topo + bs = \"re\"": assignment is deprecated
```
).

So I think there's a general problem with extra arguments to `s()` and `t2()` ("extra" meaning any arguments additional to the predictors themselves).

Fourthly, I can't think of a meaningful situation where `bs = "re"` would be needed in **projpred** because the documentation at `?mgcv::smooth.terms` says:
> These are parametric terms penalized by a ridge penalty (i.e. the identity matrix). When such a smooth has multiple arguments then it represents the parametric interaction of these arguments, with the coefficients penalized by a ridge penalty. The ridge penalty is equivalent to an assumption that the coefficients are i.i.d. normal random effects.

and multilevel models are supported via **lme4** in **projpred**. (Btw, I think the descriptions for the use cases of `bs = "re"` in comment https://github.com/stan-dev/projpred/blob/d20b5420db126ed2e11af87742625c50e93ff989/R/formula.R#L87-L94 are rather confusing, given what `?mgcv::smooth.terms` says.)

Fifthly, `bs = "fs"` is made for categorical predictors with *many* levels (see `?mgcv::smooth.terms`), not "low dimensional factors", as comment https://github.com/stan-dev/projpred/blob/d20b5420db126ed2e11af87742625c50e93ff989/R/formula.R#L87-L94 currently says.

**Comment by fweber144** [comment]
Fixed in `develop`, so a corresponding label may be added here.
