### ISSUE TITLE
Inconsistency of `suggest_size()` regarding intercept

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#164]
It seems like `suggest_size()` does not always count the intercept. This may already be seen from these lines: https://github.com/stan-dev/projpred/blob/76d22a166458701d73f793dd67ef1d56e75cc0ff/R/methods.R#L772-L788 where `object$nterms_max` and `object$nterms_all` count the intercept and `max(min(res), 1)` does also if `min(res) == 0`, but `max(min(res), 1)` doesn't if `min(res) >= 1`. So shouldn't `max(min(res), 1)` be replaced by `min(res) + 1`?

However, note that `plot.vsel()` doesn't seem to count the intercept (the x-axis tick labels start at 0), so it would probably make sense to either:

* count the intercept in `plot.vsel()`, too, *or*
* don't count the intercept in `suggest_size()`.

In any case, `suggest_size()` should be consistent in itself, so for the second proposition (don't count the intercept in `suggest_size()`), I would suggest to first fix the issue described above (replace `max(min(res), 1)` by `min(res) + 1`) and then subtract 1 at the very end of `suggest_size()`.

For illustration, consider the following reprex (tested on branch `develop`):
```r
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
library(rstanarm)
myfit <- stan_glm(y ~ V1 + V2 + V3 + V4 + V5,
                  family = gaussian(),
                  data = mydat,
                  seed = 1140350788)

library(projpred)
myvs <- varsel(myfit, nclusters = 3, nclusters_pred = 5)
plot(myvs)
debugonce(suggest_size)
suggest_size(myvs)
```
With that `debugonce(suggest_size)` call, one can see the issue best when debugging until line https://github.com/stan-dev/projpred/blob/76d22a166458701d73f793dd67ef1d56e75cc0ff/R/methods.R#L770 and then inspecting `stats` in detail (and comparing the column named as in `bound` with `util_cutoff`).

**Comment by AlejandroCatalina** [comment]
I would definitely not count the Inter el as it refers to solution term and they typically don’t include the intercept.

Best,
Alejandro

**Comment by fweber144** [comment]
Ok, so that's my second proposition

> * don't count the intercept in `suggest_size()`.

I wasn't sure which of the two suggestions you would prefer since there is also issue #159.
