### ISSUE TITLE
Offset in `d_test`

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#167]
I think argument `d_test` of `varsel()` requires an additional element for the offset which then needs to be taken into account in this line: https://github.com/stan-dev/projpred/blob/16770099ae45c24a3e9b1798ec46c36218314a68/R/varsel.R#L131-L132 similar to this line: https://github.com/stan-dev/projpred/blob/16770099ae45c24a3e9b1798ec46c36218314a68/R/refmodel.R#L229

Btw, I think it would also be good to add
```r
mu_test <- unname(mu_test)
```
after the (fixed) line
https://github.com/stan-dev/projpred/blob/16770099ae45c24a3e9b1798ec46c36218314a68/R/varsel.R#L131-L132
to be consistent with https://github.com/stan-dev/projpred/blob/16770099ae45c24a3e9b1798ec46c36218314a68/R/refmodel.R#L511 (and thereby facilitate unit testing).

**Comment by fweber144** [comment]
Commit e68c6fd added `d_test$offset` outside of `family$linkinv()`. Doesn't it need to be inside?

**Comment by AlejandroCatalina** [comment]
It should be inside it must be a typo. I’ll fix it as soon as I can. Unfortunately my time has shrunk a lot so I appreciate any PRs, as I’m not sure how much time I’ll get regularly.

Best,
Alex
________________________________
