### ISSUE TITLE
Regularization affects intercept

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#169]
It seems like the regularization which is applied to GLMs (submodels of class `"subfit"`) affects the intercept:
```r
# Tested on branch `develop`.
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
library(rstanarm)
myfit <- stan_glm(y ~ 1, data = mydat, seed = 1140350788)

library(projpred)
myprj_regul_default <- project(myfit,
                               solution_terms = character(),
                               ndraws = 25)
myprjmat_regul_default <- as.matrix(myprj_regul_default)
sum(myprjmat_regul_default[, "b_Intercept"]^2)
# [1] 13.20971

myprj_regul_new <- project(myfit,
                           solution_terms = character(),
                           regul = 1e2,
                           ndraws = 25)
myprjmat_regul_new <- as.matrix(myprj_regul_new)
sum(myprjmat_regul_new[, "b_Intercept"]^2)
# [1] 3.302433

```
However, I think the intercept should not be regularized (see e.g. [here](https://stats.stackexchange.com/questions/86991/reason-for-not-shrinking-the-bias-intercept-term-in-regression) for an explanation).

**Comment by jpiironen** [comment]
If you penalize the regression coefficients, it will affect the estimated value of the intercept too, even if the intercept is not penalized. I don't think this example proves that there's something wrong necessarily. What you can try is to put a large penalization in which case the coefficients should go (close) to zero, and the intercept should be around the mean of the fitted values of the reference model. But if the intercept goes to zero, then there's something wrong.

**Comment by fweber144** [comment]
> If you penalize the regression coefficients, it will affect the estimated value of the intercept too, even if the intercept is not penalized.

Yes, that's why I chose the intercept-only model in the example.

> I don't think this example proves that there's something wrong necessarily.

Sorry, I don't see why the example is not enough. It shows that additional regularization pulls the intercept towards zero, i.e., the intercept is regularized, too. Or did I miss something? Perhaps I should have mentioned that the default `regul` is `1e-4`, so `1e2` is really additional regularization? But of course, I'll try your suggestion.

**Comment by fweber144** [comment]
Before trying your suggestion, here first a continuation for the example above:
```r
myprj_regul_new2 <- project(myfit,
                            solution_terms = character(),
                            regul = 1e5,
                            ndraws = 25)
myprjmat_regul_new2 <- as.matrix(myprj_regul_new2)
sum(myprjmat_regul_new2[, "b_Intercept"]^2)
# [1] 1.318335e-05
```
So even more regularization pulls the intercept even further to zero.

**Comment by fweber144** [comment]
Here is your suggestion applied to the example (actually, a modification of the example since some coefficients are needed to illustrate it):
```r
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
library(rstanarm)
myfit <- stan_glm(y ~ V1 + V2 + V3 + V4 + V5 + V6 + V7 + V8 + V9 + V10,
                  data = mydat,
                  prior = hs(df = 1, global_scale = 0.01),
                  seed = 1140350788)
# Take the posterior means for an easier comparison with the projected draws:
( refprd <- mean(colMeans(posterior_linpred(myfit))) )
# [1] 0.6592656

library(projpred)

# Small `regul` -----------------------------------------------------------

myprj <- project(myfit,
                 solution_terms = paste0("V", seq_len(10)),
                 ndraws = 25)
myprjmat <- as.matrix(myprj)
( prjicpt <- mean(myprjmat[, "b_Intercept"]) )
# [1] 0.2626723
# quite far from `refprd`

mean(apply(myprjmat[, grep("b_V", colnames(myprjmat))], 1, function(x) sum(x^2)))
# [1] 4.846327
# quite far from zero

# Large `regul` -----------------------------------------------------------

myprj <- project(myfit,
                 solution_terms = paste0("V", seq_len(10)),
                 regul = 1e5,
                 ndraws = 25)
myprjmat <- as.matrix(myprj)
( prjicpt <- mean(myprjmat[, "b_Intercept"]) )
# [1] 0.6373707
# close to `refprd`, as it should be

mean(apply(myprjmat[, grep("b_V", colnames(myprjmat))], 1, function(x) sum(x^2)))
# [1] 5.206574e-06
# close to zero, as it should be

```

So in the presence of coefficients (i.e., not just the intercept-only model), everything seems to be ok. Right?

But in the original intercept-only example, I would have expected that modifying `regul` does not alter the results at all. And the way the results are altered there hints at a regularization applied to the intercept (at least that's how I would interpret it).

**Comment by jpiironen** [comment]
Sorry I overlooked that in your example you had an intercept only model, my bad. I agree that the latter example works as expected, but with the intercept only model there seems to be something wrong.

**Comment by AlejandroCatalina** [comment]
Yeah I think where this is coming from, I’ll try to take a look on Monday and push a fix. My understanding is that the intercept was collapsed into the data matrix and passed as a regular predictor, therefore being affected by the regularization directly, which should not be possible.

Thanks for reporting!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fweber144** [comment]
> Sorry I overlooked that in your example you had an intercept only model, my bad.

No problem :)

> Yeah I think where this is coming from, I’ll try to take a look on Monday and push a fix. My understanding is that the intercept was collapsed into the data matrix and passed as a regular predictor, therefore being affected by the regularization directly, which should not be possible.

Great, thanks!

**Comment by fweber144** [comment]
Thanks for creating commit e01e00e. However, when I run the reprex from [the first comment](https://github.com/stan-dev/projpred/issues/169#issue-940636727) again with that fix, the intercept is still affected. Did you manage to run the reprex successfully with the fix?

**Comment by AlejandroCatalina** [comment]
Hmm, I have rerun the full reprex and it seems to be correct:

```
>  myprj_regul_new2 <- project(myfit,
                            solution_terms = character(),
                            regul = 1e5,
                            ndraws = 25)
. + > as.matrix(myprj_regul_new2
+ )
      b_Intercept    sigma
 [1,] 0.062199978 2.940468
 [2,] 0.439350131 2.914717
 [3,] 0.759296111 3.474575
 [4,] 0.746039581 2.745819
 [5,] 0.924897470 2.622580
 [6,] 0.487210990 2.777722
 [7,] 0.342845851 2.861294
 [8,] 0.622476691 2.901256
 [9,] 1.200804120 3.063506
[10,] 0.662086401 3.679813
[11,] 0.717802067 2.782296
[12,] 0.673123381 2.974055
[13,] 1.065995116 2.748388
[14,] 0.583373616 3.345733
[15,] 0.623485561 2.781717
[16,] 0.009173495 2.756211
[17,] 0.828747099 2.912426
[18,] 0.957484810 2.868417
[19,] 0.835257046 2.803412
[20,] 0.687379442 2.610571
[21,] 1.078644631 2.905292
[22,] 0.536640301 2.971809
[23,] 0.900274174 3.299459
[24,] 0.470735853 2.747234
[25,] 0.557225768 2.942039
> myprjmat_regul_new2 <- as.matrix(myprj_regul_new2)
sum(myprjmat_regul_new2[, "b_Intercept"]^2)
> [1] 13.20973
```

Can you check again?

**Comment by fweber144** [comment]
Yes, now it works for me, too. Sorry, I might have accidentally loaded an incorrect version of projpred where the fix was not included yet.
