### ISSUE TITLE
rngtools package now depends on R >= 3.6.0

### ISSUE THREAD

**Issue by jgabry** [stan-dev/projpred#17]
Unfortunately, as of the latest release of **rngtools** (which is listed in Imports for **projpred**) it now depends on R >= 3.6.0 (see https://cran.r-project.org/web/packages/rngtools/index.html), but **projpred** is listed as depending only on R >= 3.1.2. 

https://github.com/stan-dev/projpred/blob/b2a8f92f22fc246d06de663f7a8393b9d8e86a1b/DESCRIPTION#L17-L18

Because **projpred** Imports **rngtools**

https://github.com/stan-dev/projpred/blob/b2a8f92f22fc246d06de663f7a8393b9d8e86a1b/DESCRIPTION#L24

this means we should either require R >= 3.6.0 for **projpred** too or drop the dependency on **rngtools**. If possible we should do the latter because there's really no reason for **projpred** itself to require the latest R version. 

Is using **rngtools** definitely necessary? I think we may be able to do everything without it.

**Comment by bgoodri** [comment]
This may have had to do with the bias of R's PRNG before 3.6.

**Comment by jgabry** [comment]
You're probably right. I assume that's not particularly relevant for projpred though. I bet projpred could get by with some base R code for handling the setting and resetting of the seed. If @jpiironen is ok with it I can probably take care of changing this.

**Comment by jgabry** [comment]
Seems like someone already noticed this: https://github.com/renozao/rngtools/issues/3#issuecomment-487954070

**Comment by jgabry** [comment]
Is it as simple as this? 

Replace all instances of 
```r
rng_state_old <- rngtools::RNGseed()
on.exit(rngtools::RNGseed(rng_state_old))
set.seed(seed)
```
with
```r
rng_state_old <- .Random.seed
on.exit(set.seed(rng_state_old))
set.seed(seed)
```

**Comment by jpiironen** [comment]
I have to admit I don't remember anymore exactly why we introduced the rngtools dependency. I remember the way I had used R's standard random seeding tools did not give exactly the behaviour I wanted, but it is possible that this was simply a programming mistake by me. 

Anyway, @jgabry  if you have time you can simply try the fix you proposed above, there should be a test which will trigger if it causes some unexpected behaviour. I would be happy to remove the depency on rngtools.

**Comment by jgabry** [comment]
I just opened a PR #18 that I think fixes this but it would be good for someone to take a look before I merge it.

**Comment by jpiironen** [comment]
Merged the PR, closing this now.
