### ISSUE TITLE
`cv_varsel()` for GLMMs with `method = "L1"`

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#171]
`cv_varsel()` probably lacks the same check for GLMMs with `method = "L1"` as `varsel()`:
```r
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
df_gaussian <- df_gaussian[1:40, ]
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
mydat$mygroup <- gl(n = 8, k = floor(nrow(mydat) / 8),
                    labels = paste0("gr", seq_len(8)))
set.seed(457211)
mydat$noise <- rnorm(nrow(mydat))
mygroup_icpts_truth <- rnorm(nlevels(mydat$mygroup), sd = 6)
mygroup_V1_truth <- rnorm(nlevels(mydat$mygroup), sd = 6)
mydat$y <- mydat$y + mygroup_icpts_truth[as.numeric(mydat$mygroup)]
mydat$y <- mydat$y + mygroup_V1_truth[as.numeric(mydat$mygroup)] * mydat$V1
library(rstanarm)
myfit <- stan_glmer(y ~ V1 + V2 + V3 + V4 + V5 + noise + (1 + V1 | mygroup),
                    data = mydat,
                    seed = 1140350788)
library(projpred)
myvs <- varsel(myfit, method = "L1", nclusters = 2, nclusters_pred = 3,
               seed = 734523)
```
gives:
```
Error in varsel.refmodel(refmodel, ...) :
  L1 search is not supported for multilevel models.
```
In contrast,
```r
mycvvs <- cv_varsel(myfit, method = "L1", nclusters = 2, nclusters_pred = 3,
                    seed = 734523)
```
gives:
```
[1] "Repeating l1 search for 40 LOO folds..."
  |                                                                                                              |   0%
error: element-wise multiplication: incompatible matrix dimensions: 40x1 and 0x1
Error in glm_ridge_c(x, pseudo_obs, lambda, FALSE, 0, beta_start, w0,  : 
  element-wise multiplication: incompatible matrix dimensions: 40x1 and 0x1
In addition: Warning messages:
1: Some Pareto k diagnostic values are too high. See help('pareto-k-diagnostic') for details.
 
2: In Ops.factor(1 + V1, mygroup) : ‘|’ not meaningful for factors
3: In Ops.factor(1 + V1, mygroup) :
 Error in glm_ridge_c(x, pseudo_obs, lambda, FALSE, 0, beta_start, w0,  : 
  element-wise multiplication: incompatible matrix dimensions: 40x1 and 0x1 
```
Btw, apart from GLMMs, shouldn't GAMs and GAMMs (i.e., all model types except for GLMs) also raise an error in case of `method = "L1"`? Or is L1 search supported for GAMs and GAMMs?

**Comment by AlejandroCatalina** [comment]
You are correct, only GLMs can be fitted with L1 heuristic. I’ll add the check and modify the condition.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Frank Weber ***@***.***>
Sent: Wednesday, July 14, 2021 2:20:27 PM
To: stan-dev/projpred ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [stan-dev/projpred] `cv_varsel()` for GLMMs with `method = "L1"` (#171)


cv_varsel() probably lacks the same check for GLMMs with method = "L1" as varsel():

options(mc.cores = parallel::detectCores(logical = FALSE))

data("df_gaussian", package = "projpred")

df_gaussian <- df_gaussian[1:40, ]

mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))

mydat$mygroup <- gl(n = 8, k = floor(nrow(mydat) / 8),

                    labels = paste0("gr", seq_len(8)))

set.seed(457211)

mydat$noise <- rnorm(nrow(mydat))

mygroup_icpts_truth <- rnorm(nlevels(mydat$mygroup), sd = 6)

mygroup_V1_truth <- rnorm(nlevels(mydat$mygroup), sd = 6)

mydat$y <- mydat$y + mygroup_icpts_truth[as.numeric(mydat$mygroup)]

mydat$y <- mydat$y + mygroup_V1_truth[as.numeric(mydat$mygroup)] * mydat$V1

library(rstanarm)

myfit <- stan_glmer(y ~ V1 + V2 + V3 + V4 + V5 + noise + (1 + V1 | mygroup),

                    data = mydat,

                    seed = 1140350788)

library(projpred)

myvs <- varsel(myfit, method = "L1", nclusters = 2, nclusters_pred = 3,

               seed = 734523)

gives:

Error in varsel.refmodel(refmodel, ...) :

  L1 search is not supported for multilevel models.



In contrast,

mycvvs <- cv_varsel(myfit, method = "L1", nclusters = 2, nclusters_pred = 3,

                    seed = 734523)

gives:

[1] "Repeating l1 search for 40 LOO folds..."

  |                                                                                                              |   0%

error: element-wise multiplication: incompatible matrix dimensions: 40x1 and 0x1

Error in glm_ridge_c(x, pseudo_obs, lambda, FALSE, 0, beta_start, w0,  :

  element-wise multiplication: incompatible matrix dimensions: 40x1 and 0x1

In addition: Warning messages:

1: Some Pareto k diagnostic values are too high. See help('pareto-k-diagnostic') for details.



2: In Ops.factor(1 + V1, mygroup) : ‘|’ not meaningful for factors

3: In Ops.factor(1 + V1, mygroup) :

 Error in glm_ridge_c(x, pseudo_obs, lambda, FALSE, 0, beta_start, w0,  :

  element-wise multiplication: incompatible matrix dimensions: 40x1 and 0x1



Btw, apart from GLMMs, shouldn't GAMs and GAMMs (i.e., all model types except for GLMs) also raise an error in case of method = "L1"? Or is L1 search supported for GAMs and GAMMs?
