### ISSUE TITLE
Incorrect `pct_solution_terms_cv` if `validate_search = FALSE`

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#173]
Setting `validate_search = FALSE` in `cv_varsel()` may (and usually will; only special constellations of the number of observations and the number of solution terms will not raise this issue) cause incorrect `pct_solution_terms_cv`:
```r
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
library(rstanarm)
myfit <- stan_glm(y ~ V1 + V2 + V3 + V4 + V5,
                  data = mydat,
                  seed = 1140350788)
library(projpred)
mycvvs <- cv_varsel(myfit, validate_search = FALSE,
                    nclusters = 2, nclusters_pred = 3, seed = 734523)
mycvvs$pct_solution_terms_cv
```
gives
```
     size V1 V5 V3 V2 V4
[1,]    1  1  0  0  0  0
[2,]    2  2  0  0  0  0
[3,]    3  3  0  0  0  0
[4,]    4  4  0  0  0  0
[5,]    5  5  0  0  0  0
```
In contrast, this is how I would have expected `mycvvs$pct_solution_terms_cv` to be (apart from column `"size"`, a matrix of zeros, except for the lower triangular part as well as the diagonal which should be filled with ones):
```r
mat_ch <- matrix(0,
                 nrow = nrow(mycvvs$pct_solution_terms_cv),
                 ncol = ncol(mycvvs$pct_solution_terms_cv) - 1L)
mat_ch[lower.tri(mat_ch)] <- 1
diag(mat_ch) <- 1
colnames(mat_ch) <- setdiff(colnames(mycvvs$pct_solution_terms_cv), "size")
stopifnot(identical(
  mycvvs$pct_solution_terms_cv[, colnames(mat_ch)],
  mat_ch
))
```
but that last line errors, as is clear from `mycvvs$pct_solution_terms_cv` shown above.

I think there are numerous bugs/typos leading to this issue, often caused by a confusion of rows and columns of a matrix:
1. In line https://github.com/stan-dev/projpred/blob/2ed7e42ef78f69ff3b3dcd32f7e4d6da1ad99d8e/R/cv_varsel.R#L422 I think the matrix should be filled row-wise. (For example, in case of `validate_search = FALSE`, each fold should have the same solution terms.)
2. Lines https://github.com/stan-dev/projpred/blob/2ed7e42ef78f69ff3b3dcd32f7e4d6da1ad99d8e/R/cv_varsel.R#L170-L171 completely confuse/merge the dimensions of `solution_terms_cv_ch` since the previous `sapply()` call transposes the matrix and since `solution_terms` is a function (and doesn't seem to be redefined at this place), so `length(solution_terms)` returns `1`.
3. Line https://github.com/stan-dev/projpred/blob/2ed7e42ef78f69ff3b3dcd32f7e4d6da1ad99d8e/R/cv_varsel.R#L185 probably recycles `w` incorrectly since the matrix on the left side has dimensions `size` x n (with n denoting the number of CV folds) whereas `w` is (supposed to be) of length n, I think. R operates column-major-wise. And then using `sum()` in combination with lines https://github.com/stan-dev/projpred/blob/2ed7e42ef78f69ff3b3dcd32f7e4d6da1ad99d8e/R/cv_varsel.R#L176-L177 is probably also inappropriate since the matrix (over which `sum()` is applied) has `size` rows. For example, in case of `validate_search = FALSE`, it sums up to `size` (not 1). So I think `w` also needs to be divided by `size`. But the whole `w` thing is kind of confusing (see the next enumeration point).
4. Are you sure the comment https://github.com/stan-dev/projpred/blob/2ed7e42ef78f69ff3b3dcd32f7e4d6da1ad99d8e/R/cv_varsel.R#L173 is really correct? I guess the term "weights" here refers to the differing `weights` from line https://github.com/stan-dev/projpred/blob/2ed7e42ef78f69ff3b3dcd32f7e4d6da1ad99d8e/R/cv_varsel.R#L834 but do they really need to be taken into account here in `w`? If yes, then why are the weights always defined to be constant? And if the weights are constant, they could be pulled out of the `sum()` shown in the previous enumeration point to improve readability.

This issue makes me wonder whether `pct_solution_terms_cv` is correct for `validate_search = TRUE`. I think the bugs/typos described above should also have consequences for `validate_search = TRUE`, but I haven't tried it yet.

**Comment by fweber144** [comment]
If you're satisfied with commit e529ec1 and PR #188, then I think you can add the `fixed in develop` label.

**Comment by AlejandroCatalina** [comment]
Thanks!
