### ISSUE TITLE
Add AUC as option to varsel_stats()

### ISSUE THREAD

**Issue by mcol** [stan-dev/projpred#25]
Currently only the "acc"/"pctcorr" option is specific for a binary outcome, and it's not great. Despite its limitations, the AUC is defintely better. I'm preparing a PR for this, which will introduce the "auc" stat.

**Comment by avehtari** [comment]
Thanks for working on this. I would suggest adding Brier score, too (as it would be better than AUC)

**Comment by mcol** [comment]
But the Brier score is effectively already computed with option "mse", so unless I'm missing something, it should be just a matter of adding a new option to those accepted by varsel_stats/varsel_plot and update the documentation. I could do that in a separate PR if that's what you mean.

**Comment by jpiironen** [comment]
This is now implemented by #27.
