### ISSUE TITLE
Error when running cv_varsel()

### ISSUE THREAD

**Issue by sealavi** [stan-dev/projpred#304]
Running the following script
```
fit2deriv <- brm(bf(Brix.Value~. , 
            prior = set_prior(horseshoe(df = 1, scale_slab=2.5), class = "b"),
             family = Beta(link = "logit") , data =data2,
             iter = 6000, chains = 2, save_pars = save_pars(all = TRUE),backend = "cmdstanr", control = list(adapt_delta = .99))
```
`fit2_cvderiv <- cv_varsel(fit2deriv, method='forward', cv_method='loo')`

Leads to the following error 

> Error in get(family$family, mode = "function")(link = family$link) : 
>   unused argument (link = family$link)

**Comment by fweber144** [comment]
Thanks for creating the issue. Currently, projpred doesn't support the `Beta()` family (see the [vignette](https://mc-stan.org/projpred/articles/projpred.html) and the [general package documentation](https://mc-stan.org/projpred/reference/projpred-package.html)). But I admit that the error message should be more informative. I'll put this on the to-do list.

**Comment by fweber144** [comment]
This turned out to be a bug in `brms:::get_refmodel.brmsfit()` which was quite easy to fix. I have created a PR for brms: <https://github.com/paul-buerkner/brms/pull/1336>.
