### ISSUE TITLE
Error in cv_varsel with k-fold method but not with LOO

### ISSUE THREAD

**Issue by adietzel** [stan-dev/projpred#306]
Hi,

I encountered the following error message when trying to run cv_varsel() with cv_method = "kfold" on a glm fitted with stan_glm and a binomially distributed response variable:

[1] "Performing cross-validation for the reference model.."
Fitting model 1 out of 10
Error in as.character(x) : 
  cannot coerce type 'closure' to vector of type 'character'

I do not receive this error when running it with cv_method = "LOO". Non cross-validated variable selection with varsel() also works on the fitted model. This suggests to me that the fitted model is not the issue here. I also fit the model with both a student_t and a rhs prior and changed various other settings of cv_varsel() but the issue persists. The execution stops immediately. 

  `D <- length(names(data))-1
  p0 <- 5
  N <- nrow(data)
  tau0 <- p0 / (D - p0) * 1 / sqrt(N)

  formula <- as.formula(
    paste("Pres", paste(names(data)[-c(1)], collapse = " + "), 
          sep = "~"))
  
  refm_fit <- stan_glm(
    formula = formula, 
    family = binomial(),
    data = data,
    prior = hs(global_scale = tau0),
    chains = 3, iter = 3000, warmup = 500, thin = 2,
    seed = 2052109, QR = TRUE, refresh = 0
  )

cvvs <- cv_varsel(
  refm_fit,
  cv_method = "kfold", 
)`

I am new to projpred and would appreciate any suggestion of what might be going on. 
Thank you for your help.

Best

Andreas

**Comment by fweber144** [comment]
Thanks for creating the issue. This could be rstanarm issue https://github.com/stan-dev/rstanarm/issues/551. I have tweaked your reprex a bit to make it runnable:
```r

library(rstanarm)
library(projpred)

data <- mtcars
data$mpg <- rep_len(c(0, 1), nrow(data))
D <- length(names(data))-1
p0 <- 5
N <- nrow(data)
tau0 <- p0 / (D - p0) * 1 / sqrt(N)

formula <- as.formula(
  paste("mpg", paste(names(data)[-c(1)], collapse = " + "),
        sep = "~"))

refm_fit <- stan_glm(
  formula = formula,
  family = binomial(),
  data = data,
  prior = hs(global_scale = tau0),
  chains = 3, iter = 3000, warmup = 500, thin = 2,
  seed = 2052109, QR = TRUE, refresh = 0
)

cvvs <- cv_varsel(
  refm_fit,
  cv_method = "kfold",
  seed = 1234
)

```
Then I indeed get the error you described. Currently, the only workaround for https://github.com/stan-dev/rstanarm/issues/551 I know of is to replace the `formula` object in your `stan_glm()` call by its content, i.e.:
```r
refm_fit <- stan_glm(
  formula = mpg ~ cyl + disp + hp + drat + wt + qsec + vs + am + gear + carb,
  family = binomial(),
  data = data,
  prior = hs(global_scale = tau0),
  chains = 3, iter = 3000, warmup = 500, thin = 2,
  seed = 2052109, QR = TRUE, refresh = 0
)
```
Then the `cv_varsel()` call works, at least on my machine.

**Comment by fweber144** [comment]
Closing now because this seems to be an rstanarm issue. If you don't think so, just tell me and we'll re-open it.

**Comment by adietzel** [comment]
Thanks a lot. This fixed the issue.

**Comment by adietzel** [comment]
Hi Frank, 

I have a follow-up on this issue of parsing the formula statement to stan_glm() and then cv-varsel(). I have followed your advice and had success with it. However, I am running this script for 100+ different species, for some of which some predictor variables are constant and therefore have to be removed from the data before fitting the stan GLM. I can parse the formula argument to stan_glm just fine (formula = formula) but when cv_varsel() uses the fitted stan object I run into errors described in previous posts of this issue. 

According to this reply by Alejandro Catalina to a similar issue cv_varsel() should work with a fitted stan object that had the formula parsed as an argument rather than stated explicitly. https://issuemode.com/issues/stan-dev/projpred/2194026

Is there any way I could programmatically parse a changing formula argument to stan_glm and then have it work for cv_varsel as well?

Thanks so much for your help. 
Best

Andreas

**Comment by fweber144** [comment]
Yes, I think `cv_varsel()` applied to a brms reference model with a programmatically constructed formula should work. For rstanarm reference models with a programmatically constructed formula, LOO CV (i.e., `cv_varsel(<...>, cv_method = "LOO")`) should work. Basically, only K-fold CV for rstanarm reference models with a programmatically constructed formula should be affected by https://github.com/stan-dev/rstanarm/issues/551.
