### ISSUE TITLE
Feature request: Extend projpred to support beta and gamma distributions 

### ISSUE THREAD

**Issue by sealavi** [stan-dev/projpred#313]
I often work with proportional data as well as skewed data, and would really appreciate the ability to assess variable importance such as via cv_varsel(). Would it be possible to extend projpred to support more distributions, at least beta and gamma?

**Comment by fweber144** [comment]
Yes, we (or rather @AlejandroCatalina and now @yannmclatchie) are currently working on a so-called latent projection which should be able to cover these families. The started code for this may be found in branch [`latent_projection`](https://github.com/stan-dev/projpred/tree/latent_projection). There is also a preprint at <https://arxiv.org/abs/2109.04702>.

**Comment by fweber144** [comment]
projpred v2.4.0 introduced the latent projection that I mentioned. For details, see the new [latent-projection vignette](https://mc-stan.org/projpred/articles/latent.html).
