### ISSUE TITLE
Unable to install from GitHub on M1 Mac

### ISSUE THREAD

**Issue by andrewdigby** [stan-dev/projpred#315]
I have inherited code from @AlejandroCatalina which makes use of the function `projpred:::linear_multilevel_mle`, which is not in the CRAN version.

```
ref <- init_refmodel(fit_original,  data = data, formula = formula, family = gaussian(),ref_predfun = ref_predfun, div_minimizer = projpred:::linear_multilevel_mle,proj_predfun = projpred:::linear_multilevel_proj_predfun, dis = dis_latent,extract_model_data = extract_model_data, cvfun = ref_original$cvfun )
Error in init_refmodel(fit_original, data = data, formula = formula, family = gaussian(),  :   object 'linear_multilevel_mle' not found
```

I am trying to install the `develop` branch from GitHub, but am having problems with a missing `emutls_w` library:

```
> library(githubinstall)
> gh_install_packages("projpred", ref = "develop")

✓  checking for file ‘/private/var/folders/66/yt9hj0195jq6j5mzj70_3n480000gn/T/RtmpC8GnO6/remotes13e8c4c3e562/stan-dev-projpred-d831b21/DESCRIPTION’ ...
─  preparing ‘projpred’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘projpred’ ...
   ** using staged installation
   ** libs
   clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
   clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c glmfun.cpp -o glmfun.o
   clang++ -arch arm64 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o projpred.so RcppExports.o glmfun.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.2.0/11.0.0 -L/opt/R/arm64/gfortran/lib -lgfortran -lemutls_w -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.2.0/11.0.0'
   ld: library not found for -lemutls_w
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [projpred.so] Error 1
   ERROR: compilation failed for package ‘projpred’
─  removing ‘/private/var/folders/66/yt9hj0195jq6j5mzj70_3n480000gn/T/Rtmp9QpgI6/Rinst144a325cddb5b/projpred’
         -----------------------------------
   ERROR: package installation failed
```

The reason is that I have `/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin21/12.1.0/libemutls_w.a`  (at `aarch64-apple-darwin21/12.1.0` rather than `aarch64-apple-darwin20.2.0/11.0.0`).

Please can you tell me:

1. On which branch can I find the function `linear_multilevel_mle`?
2. If you have any suggestions for how to install to a M1 Mac: particularly how to reset the library path for `emutls_w`?

Many thanks for your help, and apologies for the lack of reproducible code (which I don't think would be helpful here).

**Comment by fweber144** [comment]
> Please can you tell me:
> 
>     1. On which branch can I find the function `linear_multilevel_mle`?

If you really need it, then I guess taking the code right before PR #230 is the way to go. But projpred now has `projpred:::divmin()` as its unified divergence minimizer (see PR #230), so I would try using that first.

>     2. If you have any suggestions for how to install to a M1 Mac: particularly how to reset the library path for `emutls_w`?

Sorry, I have no experience with and no access to an M1 Mac. Perhaps @AlejandroCatalina or @yannmclatchie? If they can't help out, you could ask at <https://discourse.mc-stan.org/>. But why do you need the `develop` version? I would recommend the most recent CRAN release or branch `master` instead. Perhaps installing from CRAN works?

**Comment by AlejandroCatalina** [comment]
I don’t have experience installing `projpred` on an M1 mac unfortunately. Regarding `linear_multilevel_mle` I agree it makes sense to try using `divmin` instead, but I’m not sure of the required changes, if any, I would need to take a deeper look.

From: Frank Weber ***@***.***>
Date: Monday, 9. May 2022 at 9.51
To: stan-dev/projpred ***@***.***>
Cc: Alejandro Catalina ***@***.***>, Mention ***@***.***>
Subject: Re: [stan-dev/projpred] Unable to install from GitHub on M1 Mac (Issue #315)

Please can you tell me:

1. On which branch can I find the function `linear_multilevel_mle`?

If you really need it, then I guess taking the code right before PR #230<https://github.com/stan-dev/projpred/pull/230> is the way to go. But projpred now has projpred:::divmin() as its unified divergence minimizer (see PR #230<https://github.com/stan-dev/projpred/pull/230>), so I would try using that first.

2. If you have any suggestions for how to install to a M1 Mac: particularly how to reset the library path for `emutls_w`?

Sorry, I have no experience with and no access to an M1 Mac. Perhaps @AlejandroCatalina<https://github.com/AlejandroCatalina> or @yannmclatchie<https://github.com/yannmclatchie>? If they can't help out, you could ask at https://discourse.mc-stan.org/. But why do you need the develop version? I would recommend the most recent CRAN release or branch master instead. Perhaps installing from CRAN works?

**Comment by andrewdigby** [comment]
Thanks @fweber144 and @AlejandroCatalina. I've got `init_refmodel` running with `divmin`. I now just need a replacement for `projpred:::linear_multilevel_mle` - any ideas gratefully received!

Thanks.

**Comment by fweber144** [comment]
You mean you now need a replacement for `projpred:::linear_multilevel_proj_predfun()`? That is `projpred:::subprd()` now.

**Comment by fweber144** [comment]
> Sorry, I have no experience with and no access to an M1 Mac. Perhaps @AlejandroCatalina or @yannmclatchie?

Unfortunately, @yannmclatchie also doesn't have access to an M1 Mac. So you would have to try my other suggestions:

> If they can't help out, you could ask at https://discourse.mc-stan.org/. But why do you need the `develop` version? I would recommend the most recent CRAN release or branch `master` instead. Perhaps installing these works?

**Comment by AlejandroCatalina** [comment]
The code we need to reproduce was written using develop features that are
actually on workflow branch. So I think using that branch should solve the
issues. I don’t have access to M1 mac either so I can’t help there.

**Comment by andrewdigby** [comment]
Thanks @fweber144 and @AlejandroCatalina. 

For future reference if anyone has similar problems: I got the `workflow` branch installed by
1. Installing `gfortran` from [here](https://mac.r-project.org/tools/)
2. Adding the following to `Makevars`:

```
FLIBS=-L/path/to/libgfortran.dylib
```

See [here](https://stackoverflow.com/questions/29992066/rcpp-warning-directory-not-found-for-option-l-usr-local-cellar-gfortran-4-8/29993906#29993906) for more details.
