### ISSUE TITLE
projpred with weibull family - latent_projection branch

### ISSUE THREAD

**Issue by demodw** [stan-dev/projpred#332]
Hi,

I tried to follow the steps on the latent_projection branch for how to use projpred with a time to event model (https://github.com/stan-dev/projpred/blob/latent_projection/vignettes/latent.Rmd#L127). However, I just get the follow error:

`Error in projpred::extend_family(family) : 
  Family 'weibull' is not supported by projpred.`

Are there any additional steps that I'm missing?

Thanks in advance.

**Comment by fweber144** [comment]
For me, the time-to-event example from that vignette works. Are you sure you installed projpred from that `latent_projection` branch?

In any case, the latent projection is under active development and not finished yet. We hope to progress soon on this.

**Comment by demodw** [comment]
Yes, I copy-pasted the code line-by-line and updated suggested packages. The current installed version is:

`
projpred       * 2.0.5.9000 2022-07-13 [1] Github (stan-dev/projpred@beeaa6c)
`

It seems like there is no function extending the weibull family in the `extend_family.R´ code (https://github.com/stan-dev/projpred/blob/022159f97f6c189ed1c7e9ac0976b484291d744c/R/extend_family.R), could this be the reason? Although, to be fair, I actually could not find a function ever extending it in the history..

**Comment by fweber144** [comment]
> It seems like there is no function extending the weibull family in the `extend_family.R´ code (https://github.com/stan-dev/projpred/blob/022159f97f6c189ed1c7e9ac0976b484291d744c/R/extend_family.R), could this be the reason? Although, to be fair, I actually could not find a function ever extending it in the history..

No, there is no function for extending the Weibull family and that's correct because the latent projection is used for it (the preprint for the methodology behind that is at <https://arxiv.org/abs/2109.04702>).

**Comment by fweber144** [comment]
> Yes, I copy-pasted the code line-by-line and updated suggested packages. The current installed version is:
> 
> `projpred * 2.0.5.9000 2022-07-13 [1] Github (stan-dev/projpred@beeaa6c)`
> 
> [...]
> 
> Edit: seems to be some sort of Windows problem. Tried the same on our Linux cluster and it works.

Hm, that's strange. For me, it also works on Windows (for my comment [above](https://github.com/stan-dev/projpred/issues/332#issuecomment-1179718109), I was running it on Linux). Could you post the exact code you are running, together with the output of `sessioninfo::session_info()`?

**Comment by demodw** [comment]
Did a (completely) fresh install and it works now, sorry for the trouble!
