### ISSUE TITLE
cv_varsel error in development version

### ISSUE THREAD

**Issue by sor16** [stan-dev/projpred#343]
Hi,

I noticed that cv_varsel throws an error in the development version for forward search, refit_prj=F and validate_search=F. The same code works in the CRAN version. See below for a reproducible example. 

```
#requires forking the repo and run devtools::load_all() to get development version
library(brms)
dat=data.frame(y = rnorm(100), x1 = rnorm(100), x2 = rnorm(100), x3 = rnorm(100))
ref_mod <- brm(y ~ x1 + x2 + x3,data=dat,refresh=0)
cv_select_prj <- cv_varsel(ref_mod,method='forward',refit_prj=F,validate_search=F) #Error
```
The error message reads

```Error in log_lik_sub + lw_sub : non-conformable arrays```

After debugging I found that the error occurs in line 426 in cv_varsel.R in the function loo_varsel. I don't quite understand the details of what is happening in the code but it seems to be a normalization step on the sum of lw_sub and log_lik_sub  but they are of different dimensions (lw_sub is 400x100 and log_lik_sub is 20x100), causing the error. Do you have an idea what could be going on here?

Cheers,
Sölvi

**Comment by fweber144** [comment]
Hi Sölvi,

Thanks for creating the issue. The reason for why you experience this with the `master` branch, but not the CRAN version is probably PR #267 in combination with PR #325 (the latter does not exist in the CRAN version yet). The point is `refit_prj = FALSE` here which causes the submodel fits from the search to be re-used for the performance evaluation. By default, search and performance evaluation have different numbers of projected draws (20 clusters and 400 thinned draws, respectively), thus the differing dimensions of the matrices `log_lik_sub` and `lw_sub`. I'll try to fix this asap.

Best,
Frank

**Comment by fweber144** [comment]
Oh, and this also shows that we definitely need thorough unit tests for argument `refit_prj`. I wanted to wait with them until #168 is resolved, but perhaps I should add them sooner.

**Comment by fweber144** [comment]
Should be fixed now. Thanks again for creating the issue.
