### ISSUE TITLE
Fixing certain terms to be included in all submodels in cv_varsel in a high dimensional setting

### ISSUE THREAD

**Issue by sor16** [stan-dev/projpred#346]
Hi again,

In the current implementation of cv_varsel, fixing certain terms to be included in all submodels can be done by using the search_terms argument. This is done by letting search_terms be a vector of all model formulas you wish cv_varsel to consider. This allows for much flexibility for the user, but can become highly inefficient when the number of terms under consideration is large. Assume e.g. that I have a treatment variable t and a set of 100 covariates that I want to do variable selection on, while including t in each submodel. To make sure t is included in all submodels, I need to define the search_terms vector as described above. In code:
```
get_search_terms <- function(p){
  search_terms <- c()

  for(i in 1:p){
    search_terms <- c(search_terms, apply(combn(idx_select[1:n_select], i), 2, function(x) paste(paste0("x", x),collapse = "+")))
  }
  #add model only containing t and also add t to every formula
  search_terms <- c('t',paste0('t+', search_terms))
}
```
This runs fine for small p i.e. p < 20. But when I let p=100, this takes forever and will overflow, which is maybe expected, as the number of all submodels is 2^p. As my use case is not terribly complicated and I would argue that it is useful, I suggest that an additional argument to cv_varsel called must_include is added, which would be a character vector of terms that should be included in every submodel in the search. This way, I would avoid having to specify the search_terms vector. I would be happy to contribute to such an addition if there is interest in this.

Cheers,
Sölvi

**Comment by fweber144** [comment]
Yes, this is a useful feature request. Thank you for creating it. Contributions in implementing this are very welcome, of course.

**Comment by fweber144** [comment]
I'm still thinking about the most appropriate name for this argument. Perhaps it would be possible to find a name that signals the relationship to `search_terms`, e.g., `search_terms_forced`?

**Comment by fweber144** [comment]
Just for future reference: The reprex above does not run through because object `idx_select` is not defined. A working (and slightly modified) reprex is:
``` r
get_search_terms <- function(n_predictors) {
  search_terms <- unlist(lapply(seq_len(n_predictors), function(m_predictors) {
    lapply(combn(n_predictors, m = m_predictors, simplify = FALSE),
           function(idxs_predictors) {
             paste(paste0("X", idxs_predictors), collapse = " + ")
           })
  }))
  search_terms <- c("A", paste("A +", search_terms))
  return(search_terms)
}
( search_terms <- get_search_terms(3) )
#> [1] "A"                "A + X1"           "A + X2"           "A + X3"          
#> [5] "A + X1 + X2"      "A + X1 + X3"      "A + X2 + X3"      "A + X1 + X2 + X3"
```

<sup>Created on 2023-06-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by fweber144** [comment]
Oh, I now realized that we don't even need to combine all the optional predictor terms via `+`. Instead, it is sufficient to create the `search_terms` consisting of the forced predictor terms, then a `+`, and then taking each of the optional predictor terms in turn. This reduces the size of the `search_terms` vector considerably and means that to solve this issue, we can simply offer the following helper function:
``` r
get_search_terms_forced <- function(forced_terms, optional_terms) {
  forced_terms <- paste(forced_terms, collapse = " + ")
  return(c(forced_terms, paste0(forced_terms, " + ", optional_terms)))
}
get_search_terms_forced(forced_terms = c("A", "B"),
                        optional_terms = paste0("X", seq_len(3)))
#> [1] "A + B"      "A + B + X1" "A + B + X2" "A + B + X3"
```

<sup>Created on 2023-08-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I realized this in the context of [this Stan Discourse thread](https://discourse.mc-stan.org/t/projpred-non-convergence-of-predictive-performance-with-reference-model/31916) and its reprex at https://github.com/l-gorman/projpred_issue_reprex. Thanks to @l-gorman for taking me there!

Full reprex based on `varsel()`:
``` r
data("df_gaussian", package = "projpred")
df_gaussian <- df_gaussian[1:29, ]
dat <- data.frame(y = df_gaussian$y, df_gaussian$x)
suppressPackageStartupMessages(library(rstanarm))
rfit <- stan_glm(y ~ X1 + X2 + X3 + X19 + X20,
                 data = dat,
                 chains = 1,
                 iter = 500,
                 seed = 1140350788,
                 refresh = 0)

suppressPackageStartupMessages(library(projpred))
options(projpred.extra_verbose = TRUE)

get_search_terms_forced <- function(forced_terms, optional_terms) {
  forced_terms <- paste(forced_terms, collapse = " + ")
  return(c(forced_terms, paste0(forced_terms, " + ", optional_terms)))
}
search_terms_forced <- get_search_terms_forced(
  forced_terms = c("X19", "X20"),
  optional_terms = paste0("X", seq_len(3))
)

vs <- varsel(rfit,
             nclusters = 3,
             nclusters_pred = 5,
             search_terms = search_terms_forced,
             seed = 123124)
#> -----
#> Running the search ...
#>   Projecting onto 1
#>   Projecting onto X19 + X20
#> 40% of terms selected: 1 + X19 + X20
#>   Projecting onto X19 + X20 + X1
#>   Projecting onto X19 + X20 + X2
#>   Projecting onto X19 + X20 + X3
#> 60% of terms selected: 1 + X19 + X20 + X1
#>   Projecting onto X19 + X20 + X1 + X2
#>   Projecting onto X19 + X20 + X1 + X3
#> 80% of terms selected: 1 + X19 + X20 + X1 + X3
#>   Projecting onto X19 + X20 + X1 + X3 + X2
#> 100% of terms selected: 1 + X19 + X20 + X1 + X3 + X2
#> -----
#> -----
#> For performance evaluation: Re-projecting onto the submodels along the solution path ...
#>   Projecting onto 1
#>   Projecting onto X19 + X20
#>   Projecting onto X19 + X20 + X1
#>   Projecting onto X19 + X20 + X1 + X3
#>   Projecting onto X19 + X20 + X1 + X3 + X2
#> -----
ranking(vs)
#> $fulldata
#> [1] "X19 + X20" "X1"        "X3"        "X2"       
#> 
#> $foldwise
#> NULL
#> 
#> attr(,"class")
#> [1] "ranking"
```

<sup>Created on 2023-08-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by fweber144** [comment]
When adding this helper function, a better name might be `force_search_terms()` (instead of `get_search_terms_forced()`).
