### ISSUE TITLE
Problem with projpred for a simple brms model

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/projpred#348]
With the latest CRAN and github versions of projpred, I can the following error on a simple brms model. @fweber144 can you see whether this is a bug in projpred or rather a problem in how brms sets of the reference model?

```R
library(brms)
library(projpred)

fit <- brm(count ~ zAge + zBase * Trt,
             data = epilepsy, family = poisson())

# happens both in varsel and cv_varsel
vs <- varsel(fit)
# Error in x[, colnames(x)[search_path$solution_terms[indices]], drop = FALSE] : 
#   subscript out of bounds
```

**Comment by fweber144** [comment]
Should be fixed now. Thanks for reporting!
