### ISSUE TITLE
Adding bernoulli() to extend_family()

### ISSUE THREAD

**Issue by adietzel** [stan-dev/projpred#352]
While the bernoulli() distribution is now supported by propred via brms::bernoulli(), and works fine for standard calls to cv_varsel(), it is currently not listed in the extend_family() function which causes custom reference model parsed to cv_varsel() via init_refmodel() to fail. 

It would be amazing if it could be added. I presume the specifications would be very similar to the specifications of the binomial distribution but I am not sure how to implement this myself in extend_family().
Thanks

Andreas

**Comment by fweber144** [comment]
As the documentation says (correct me if I am wrong), the `brms::bernoulli()` family is supported via `brms:::get_refmodel.brmsfit()`. There, brms essentially converts it to the `binomial()` family, so support for `brms::bernoulli()` in `init_refmodel()` is not necessary.

**Comment by adietzel** [comment]
You are absolutely correct. My apologies for missing this bit. Using brms:::get_refmodel.brmsfit() works perfectly. 
Thanks for your help. 
Andreas
