### ISSUE TITLE
projpred removed from CRAN

### ISSUE THREAD

**Issue by strengejacke** [stan-dev/projpred#37]
I just realized due to failing CRAN checks of one of my packages that the "projpred" package is no longer on CRAN. Are you in contact with the CRAN team regarding this issue (planning to put it back on CRAN), or will this package become orphaned?

**Comment by jpiironen** [comment]
I'm working on it, let's hope we get it there back soon. I'll let you know when I have more information.

**Comment by strengejacke** [comment]
Thanks!

**Comment by jpiironen** [comment]
Projpred is now back in CRAN https://cran.r-project.org/web/packages/projpred/index.html.
