### ISSUE TITLE
error in installation in Mac OS M2

### ISSUE THREAD

**Issue by salvadorrdm** [stan-dev/projpred#380]
Hi, 

I've been trying to install it but get this message.

Thanks for the advice and congratulations for the package.

Salvador

> devtools::install_github("stan-dev/projpred", build_vignettes = TRUE)
Downloading GitHub repo stan-dev/projpred@HEAD
── R CMD build ──────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/76/5gbc3tdn1lb7hcrb9gp_j2lh0000gn/T/Rtmp2orfvY/remotes597f74d3229e/stan-dev-projpred-f9e35d1/DESCRIPTION’ ...
─  preparing ‘projpred’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
         -----------------------------------
─  installing *source* package ‘projpred’ ...
   ** using staged installation
   ** libs
   clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
   clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c glmfun.cpp -o glmfun.o
   clang++ -arch arm64 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o projpred.so RcppExports.o glmfun.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1 -L/opt/R/arm64/gfortran/lib -lgfortran -lemutls_w -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1'
   ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib'
   ld: library not found for -lgfortran
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [projpred.so] Error 1
   ERROR: compilation failed for package ‘projpred’
─  removing ‘/private/var/folders/76/5gbc3tdn1lb7hcrb9gp_j2lh0000gn/T/RtmpWaLOdt/Rinst61e26a282d5d/projpred’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'projpred' from GitHub:
  ! System command 'R' failed
>

**Comment by andrjohns** [comment]
For compiling R packages with fortran code on Apple Silicon, you need to install the R project's GNU fortran compiler. The installer and setup instructions are available on this page: https://mac.r-project.org/tools/

**Comment by fweber144** [comment]
Thanks, @andrjohns, for helping out. For @salvadorrdm, perhaps [this](https://github.com/stan-dev/projpred/issues/315#issuecomment-1127202729) might also be helpful.

**Comment by salvadorrdm** [comment]
Thanks a lot, I installed the R project's GNU fortran compiler and it works now.
