### ISSUE TITLE
Recent CRAN failures

### ISSUE THREAD

**Issue by HenrikBengtsson** [stan-dev/projpred#398]
Hello,

I looked into why **projpred** started to fail package checks after my update to **doFuture** 1.0.0.  From my troubleshooting, I do not believe this is related to the **doFuture** update.  I also do not see how the actually updates in **doFuture** would be able to affect your back this way.  Instead, I think this is related to recent updates to R itself that apply to the R 4.3.0 and R 4.4.0 branches.

Since I already investigated time in this, and followed the progression thus far, I figured sharing my notes could help you track this down on your end.

Looking at <https://cran.r-project.org/web/checks/check_results_projpred.html> on 2023-03-27, it fails on R-devel (=R 4.4.0) and R-patched (=R 4.3.0), but not elsewhere.  The error on 'r-release-windows-x86_64' is an installation error, so not a check error.

Right now, 'r-devel-linux-x86_64-debian-clang' does not fail. It runs R Under development (unstable) (2023-03-22 r84023).  It fails on 'r-patched-linux-x86_64', which runs R version 4.3.0 alpha (2023-03-24 r84048), and on all other R-devel which run even newer revisions.

So, my best guess it that this due to some update in R between r84023 and r84048.

The following files have changed between r84023 and r84048;

```sh
$ git diff --name-only 9e9bf0c05 a1266fd9 src/library/*/R/
src/library/stats/R/family.R
src/library/stats/R/glm.R
src/library/stats/R/plot.lm.R
src/library/stats/R/vcov.R
src/library/tools/R/QC.R
src/library/utils/R/citation.R
```

If my hypothesis is correct, then the ERRORs should only show up on check servers running R (>= 4.3.0), but not on those running R (<= 4.2.3).

**Comment by fweber144** [comment]
Thank you very much, this is really helpful. And it looks like something which indeed needs an adjustment. I'll have look at this asap.
