### ISSUE TITLE
Uncertainty in statistics relative to the reference model(?)

### ISSUE THREAD

**Issue by StaffanBetner** [stan-dev/projpred#46]
If I compare the plot of the absolute values and of the relative values there is something off with the uncertainty calculations. If seems like it is calculated as relative to the mean of the statistic of the reference model, instead of taking the observation-wise difference, which should make the delta statistic collapse unto the baseline for the reference model. I haven't looked at the code yet, but it if is calculated in this way it will bias the length of the uncertainty intervals. Although I might have misunderstood what the reference model is. 

Compare the two plots here:
![image](https://user-images.githubusercontent.com/8129424/75680394-cf878580-5c91-11ea-8299-f085869b00a4.png)

![image](https://user-images.githubusercontent.com/8129424/75680413-da421a80-5c91-11ea-8529-ec136ff7a469.png)

**Comment by jpiironen** [comment]
If your reference model is the model with 10 variables, then yes, the relative difference should collapse more or less to zero at 10 variables. However, if you run the selection with default settings, then the projection uses I think 5-cluster projection by default, which introduces some discrepancy, meaning that projecting even the reference model onto itself is not exact. If you set argument `ns` to the number of posterior samples in your reference model, then the projection onto the reference model should be exact (this will be computationally slower though).

**Comment by jpiironen** [comment]
@StaffanBetner Is your problem solved, so can we close this issue?

**Comment by jpiironen** [comment]
Closing this now
