### ISSUE TITLE
Clarify doc for refit_prj

### ISSUE THREAD

**Issue by avehtari** [stan-dev/projpred#489]
cv_varsel doc says:
> refit_prj: For the evaluation part, should the submodels along the predictor ranking be fitted again (TRUE) or should their fits from the search part be re-used (FALSE)?

I think this sentence would need to be clarified to avoid possible confusion with refitting meaning running MCMC. Maybe rewrite
as
> refit_prj: For the evaluation part, should the submodels along the predictor ranking be projected again using `ndraws_pred` draws or `nclusters_pred` clusters (TRUE) or should their projections from the search part, which used `ndraws` draws or `nclusters` clusters, be re-used (FALSE)?

**Comment by fweber144** [comment]
I agree. Just want to add that there might be more places (in the docs and/or vignettes) where terminology such as "submodel fit" or "fitting a submodel" is used. Those places would have to be adapted, too.

**Comment by fweber144** [comment]
For

> should the submodels along the predictor ranking be projected again

something like

> should the projections onto the submodels along the predictor ranking be performed again

might be a little more appropriate, as we are projecting the reference model onto the submodels.
