### ISSUE TITLE
Implementation of the Gamma distribution

### ISSUE THREAD

**Issue by henningte** [stan-dev/projpred#58]
Hi,

I am interested in using projpred with a Gamma distributed dependent variable for a current research project.

I have seen (as far as I can judge this) from the source code files that the implementation for the Gamma distribution is in an advanced stage and I was interested if a full implementation is planned in the next time. 

I think that my knowledge is unfortunately not deep enough to give it a try myself.

**Comment by AlejandroCatalina** [comment]
Hi, 

I'm on vacation currently until July 27th, so I won't be able to provide a fast solution. Nonetheless, I can tell you that finishing support for gamma distributions is on our roadmap but not top priority right now. I will, however, take a close look at this and report back on the status.

Thanks for the interest and feedback!

**Comment by henningte** [comment]
That's no problem at all. I just wanted to decide if it is worth waiting with the analyses until the Gamma distribution is implemented or not, but I have no urgent problems with the current implementation (the models look fine). 

I'll try the Gamma distribution later then, as soon as it is available (I have other analyses also with Gamma distributed dependent variables). 

Thanks for the reply!

**Comment by IvarKolvoort** [comment]
Hi,

I wondered whether there is any update on the implementation of the gamma distribution in projpred. Wanting to use it for a current project.

Thanks for all the great work!

**Comment by AlejandroCatalina** [comment]
Hi,

Thanks for your interest. We are well underway on our implementation for models outside of the exponential family. This is to say that we are not implementing specific families per se but many models should be readily available soon.

Basically, we are bringing support to all models of the form:

**Comment by IvarKolvoort** [comment]
Hi,

Thanks for you quick response. Sorry it is not completely clear to me yet, I'm quite the novice at this. I thought the Gamma distribution was part of the exponential family, you seem to imply it is not.  Can `p()` be any function? Does a regression using a Gamma distributed dependent variable with a log link fall under the form you specify?

**Comment by AlejandroCatalina** [comment]
I am sorry I didn't think twice about my answer!! 

The answer is valid from a different angle: we are not going to implement family specific solutions but this approach will work as well for families not implemented that belong in the exponential family.

Sorry about the confusion.

**Comment by IvarKolvoort** [comment]
Ah great, that is clear now :) Thanks for the response and will be looking out for that update!
