### ISSUE TITLE
Does not work with `rstanarm::stan_lm`

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/projpred#6]
The `varsel` function does not throw an error but does not work correctly when given an object produced by `stan_lm` in the **rstanarm** package. The reason seems to be that in this part of the `.extract_vars` function:
```
dis = unname(e[["aux"]]) %ORifNULL% rep(NA, 
            nrow(e$beta))[perm_inv]
```
`dis` becomes a vector of `NA` because the auxiliary parameter is called "sigma" rather than "aux".

**Comment by paasim** [comment]
Thanks for reporting this, fixed in 0eb0f882102579f430c54f52ef69082eafbf7cb8.
