### ISSUE TITLE
Inappropriate warning messages

### ISSUE THREAD

**Issue by andymilne** [stan-dev/projpred#62]
Using projpred 2.0.0, if I run

```
  pulse_tap_cvs <-
    cv_varsel(
      mdl_pulse_tap_ref_rstan,
      # nterms_max = 39,
      nloo = 2000)
```

I get the following warnings, all of which seem inappropriate (the third is inappropriate because it is confusing to be warned that I should use cv_varsel when I already am, and also leaves me wondering whether I can still trust the results and what exactly are the implications of the performance of the projected model being misleading):

```
Warning messages:
1: Using formula(x) is deprecated when x is a character vector of length > 1.
  Consider formula(paste(x, collapse = " ")) instead. 
2: In cv_varsel.refmodel(refmodel, ...) :
  K provided, but cv_method is LOO.
3: In varsel.refmodel(refmodel, method = method, ndraws = ndraws, nclusters = nclusters,  :
  The performance of the projected model seems to be misleading, we recommend checking the reference model as well as running `varsel` with a larger `ndraws_pred` or `cv_varsel` for a more robust estimation.
```

**Comment by AlejandroCatalina** [comment]
Good you reported this! So, the only worrying message is sometimes the one pointing at a misleading result. Basically, this warning is triggered by varsel as well, and given that cv_varsel is also calling varsel underneath, the warning can appear as well. I’ll fix all of them!

Best,
Alejandro

**Comment by AlejandroCatalina** [comment]
Fixed in develop.
