### ISSUE TITLE
get_refmodel: mismatch of arguments in init_refmodel 

### ISSUE THREAD

**Issue by StaffanBetner** [stan-dev/projpred#64]
When playing around and trying whether e.g. lm models works, I found a mismatch here: https://github.com/stan-dev/projpred/blob/47ad88b09af2e2cc96b7e2141a2afab662a3aa70/R/refmodel.R#L230

Compare to https://github.com/stan-dev/projpred/blob/47ad88b09af2e2cc96b7e2141a2afab662a3aa70/R/refmodel.R#L331 where y is missing

**Comment by AlejandroCatalina** [comment]
We don’t really need y in any of those places. I’m earlier versions y was passed independently so we kept it in the default method for other object types that we don’t know beforehand. But it’s true we could remove it and just pass y along with the data. I’ll refs for that! Thanks for reporting

Best,
Alejandro

**Comment by AlejandroCatalina** [comment]
Cherry picked to master.
