### ISSUE TITLE
Incorrect formula for deviance of Gaussian family?

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#81]
Shouldn't this line:
https://github.com/stan-dev/projpred/blob/dc1c3e473c8df2298e956c406499ddac941e5c5f/R/extend_family.R#L139
read
```r
-2 * weights * (-0.5 / dis^2 * (y - mu)^2 - log(dis)) 
```
i.e. taking `dis^2` instead of `dis` in the middle? If I understood projpred's internal code correctly, then `dis` is the standard deviation here, not the variance. And the deviance is -2 times the (weighted) log likelihood.

**Comment by jpiironen** [comment]
Yeah, looks like a mistake if `dis` means std (as I think it does).

**Comment by AlejandroCatalina** [comment]
I pushed a hot fix to develop.

Best,
Alejandro
