### ISSUE TITLE
Thinning or subsampling posterior draws

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#86]
The current behavior of `.get_refdist()` is to "thin" the posterior draws in case of `is.null(nclusters) && !is.null(ndraws)` (i.e. also for `nclusters == NCOL(refmodel$mu)`). As suggested in `.get_refdist()`'s comments, it might be safer to subsample the posterior draws in that case. Thinning might also make sense in certain circumstances, so another option would be to offer both (thinning as well as subsampling) and let the user decide. Personally, I would say the default should be subsampling, though.

In case of thinning, the `.get_refdist()` code could be simplified: The case https://github.com/stan-dev/projpred/blob/0cabd73548eec32e9b675f15cd39d377a40f180a/R/misc.R#L292-L301 could be included in the `else if (!is.null(ndraws)) {[...]}` case above it. To do so, setting `ndraws` to `S` if `is.null(ndraws)` (and using `else {` instead of `else if (!is.null(ndraws)) {`) should suffice.

In case of subsampling, would it make sense to have a separate case for `ndraws == S` so that the order of the posterior draws can be preserved in that case? I can't think of a situation where this would be necessary, but perhaps you can.

(Mentioned [here](https://github.com/fweber144/projpred/blob/5088cbdfca26ccb58c366e4d31e1b2203ffc84d1/R/misc.R#L274-L276) and [here](https://github.com/fweber144/projpred/blob/5088cbdfca26ccb58c366e4d31e1b2203ffc84d1/R/misc.R#L295-L298).)

**Comment by AlejandroCatalina** [comment]
I cannot think of a situation where order is instrumental, so I have set the default to subsampling and left the option for thinning out for now. I might make a commit next to include a thinning scenario. I have also simplified the code as you suggested. Thanks (the commit will appear soon).

**Comment by fweber144** [comment]
Thanks for addressing this. I guess line https://github.com/stan-dev/projpred/blob/02cd50db76b0f2d835ce8f8f39cbe94353540d64/R/misc.R#L274 can be removed now.

**Comment by fweber144** [comment]
Just to have this documented: A personal discussion revealed that thinning should be the default (addressed in commit 3ef419e2d3bbc350cfd9d70e010c3cadac5d7a43).

**Comment by fweber144** [comment]
Closing this as it's solved for my understanding. Re-open if you want/need to.
