### ISSUE TITLE
Simplification in project_submodel()?

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#88]
This is not really an issue, but could simplify debugging: In `project_submodel()`, the helper function https://github.com/stan-dev/projpred/blob/0cabd73548eec32e9b675f15cd39d377a40f180a/R/projfun.R#L14-L17 should not be necessary (`refmodel$div_minimizer()` could be used directly, at least as far as I can tell).

(Mentioned [here](https://github.com/fweber144/projpred/blob/5088cbdfca26ccb58c366e4d31e1b2203ffc84d1/R/projfun.R#L14).)

**Comment by AlejandroCatalina** [comment]
This can be indeed refactored. The reason I wrote this like it is is to defer some parameters so the actual function call is shorter and can be reused in multiple places. Right now, it's only used in one place but at the time of writing I thought for the sake of modularity this could be easier to read without all the extra fixed parameters. However, I agree this abstraction is not necessary right now but I'm leaning towards leaving it as is for the time being, although I don't have a strong objection to just remove this.

**Comment by fweber144** [comment]
From my side, you can close this if you want to. Up to you.
