### ISSUE TITLE
Linear-predictor-scaled mu_test in varsel.refmodel()

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#90]
The inverse-link (i.e. `family$linkinv()`) does not seem to be applied to object `mu_test` created in this line: https://github.com/stan-dev/projpred/blob/0cabd73548eec32e9b675f15cd39d377a40f180a/R/varsel.R#L179 Is this done on purpose? Usually, mu is on the scale of the response, not on the scale of the linear predictor, right?

(Mentioned [here](https://github.com/fweber144/projpred/blob/5088cbdfca26ccb58c366e4d31e1b2203ffc84d1/R/varsel.R#L179).)

**Comment by AlejandroCatalina** [comment]
You're right! Fixed now.
